name: ðŸ› Bug Report
description: Report a bug or unexpected behavior in Droppy
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: input
    id: version
    attributes:
      label: Droppy Version
      description: "You can find this in Settings > About"
      placeholder: "e.g., 8.1.5"
    validations:
      required: true

  - type: dropdown
    id: macos-version
    attributes:
      label: macOS Version
      options:
        - macOS 26 (Tahoe)
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - Other / Older
    validations:
      required: true

  - type: dropdown
    id: mac-type
    attributes:
      label: Mac Type
      options:
        - MacBook Pro (M-series, with Notch)
        - MacBook Air (M-series, with Notch)
        - iMac (M-series)
        - Mac Mini / Mac Studio / Mac Pro
        - MacBook Pro (Intel)
        - MacBook Air (Intel)
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you expect vs what actually happened?
      placeholder: |
        When I [action], I expected [expected behavior], but instead [actual behavior].
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open Droppy
        2. Go to...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      options:
        - Every time
        - Sometimes (50% of the time)
        - Rarely (once or twice)
        - Only happened once
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or screen recordings
      description: If applicable, add screenshots or recordings to help explain the problem
      placeholder: Drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other details that might help (crash logs, related settings, etc.)
